import redot.tweakfabric.gradle.MappingType

plugins {
    id 'redot.tweakfabric.plugin' version '1.0.4-SNAPSHOT'
    id 'io.freefair.lombok' version '9.5.0'
}

group = 'com.template'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

tweakfabric {
    targetMapping = MappingType.INTERMEDIARY
    compileDirectory = 'com.template.main'
    minecraftVersion = '1.21.8'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}